### ISSUE TITLE
Crashed with Astromine

### ISSUE THREAD

**Issue by linzexin022** [badasintended/megane#10]
Game Version: 1.16.4
Astromine Version: 1.12.0 (from github)
Megane Version: 3.1.1
[crash-2020-12-31_23.22.42-client.txt](https://github.com/badasintended/megane/files/5757598/crash-2020-12-31_23.22.42-client.txt)

**Comment by deirn** [comment]
they pulled it from cf not long after uploading it because it's buggy, and i can't support a version that they don't support either, sorry for that
