### ISSUE TITLE
Versions 3.1.4 and 3.1.5 are Not Compatible With HWYLA

### ISSUE THREAD

**Issue by Pascal204** [badasintended/megane#17]
When I try to open the game it crashes and says: "megane requires wthit" even though I have Hwyla.

**Comment by koelle25** [comment]
I have the same problem, also with currently released 3.1.5.

@Pascal204 As a workaround you can modify the following files inside the jar:
 - fabric.mod.json
 - META-INF/jars/megane-api-{version}.jar/fabric.mod.json
 - META-INF/jars/megane-runtime-{version}.jar/fabric.mod.json

In all these files replace `"wthit": "*"` with `"waila": "*"` under the `"depends"` key. Seems to work just fine for me.

**Comment by Pascal204** [comment]
lol thanks dude it works now.

**Comment by Pascal204** [comment]
lol thanks dude it works now.

**Comment by koelle25** [comment]
You're welcome :smiley: 

One thing left:
I'd say you keep this issue open/reopen it, as this behaviour IMHO should still be considered a bug.

**Comment by deirn** [comment]
mixin config broke on hwyla, but now that i think about it, the only reason it exists is for debugging purposes i don't think players even touch it so i reverted the change. sorry for the inconvenience
