### ISSUE TITLE
[1.16.5] "Could not execute entrypoint stage 'main' due to errors, provided by 'megane-runtime'!"

### ISSUE THREAD

**Issue by aking4125** [badasintended/megane#18]
Hello,

Currently getting a crash upon startup. There must be a mod conflict but the crash report isn't really helping. Megane with just WTHIT works fine. Trying to create a modpack and this crash is stopping it. Any ideas?

[crash-2021-04-05_04.32.21-client.txt](https://github.com/badasintended/megane/files/6257842/crash-2021-04-05_04.32.21-client.txt)

Here's the log if anything:

[latest.log](https://github.com/badasintended/megane/files/6257846/latest.log)

**Comment by deirn** [comment]
can you try [https://github.com/badasintended/megane/suites/2378010302/artifacts/50475218](https://github.com/badasintended/megane/suites/2378010302/artifacts/50475218)? extract it and use the biggest file

**Comment by aking4125** [comment]
That file works with the modpack!

**Comment by deirn** [comment]
alright, released it ;-)
