### ISSUE TITLE
AOF3 2.7.2 Energy and Fluid not showing.

### ISSUE THREAD

**Issue by kabadesu** [badasintended/megane#20]
I've been trying to fix a problem where energy and fluid aren't showing with wthit/megane on the AOF EU server. I've updated to the latest wthit-2.7.1-fabric, deleted the waila config directory, ensured the settings are true for showing energy/fluid, and also tried force registry for both - but still nothing shows.

It's possible there's a conflict with something else, but I'm not sure what else could be affecting this.

**Comment by deirn** [comment]
<details>
<summary>It's working for me</summary>

![2021-05-02_11 08 41](https://user-images.githubusercontent.com/21150434/116801779-03c93100-ab37-11eb-934a-443b81e27810.png)

</details>

can you run `/wailadumphandler` command and send `.minecraft/waila_handlers.md` file?
<details>
<summary>it should show something like this</summary>

# Waila Handler Dump
## Block
### Override Providers

#### `net.minecraft.class_2384`
* `mcp.mobius.waila.plugin.vanilla.InfestedBlockComponent`


### Display Item Providers

#### `net.minecraft.class_1690`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1534`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1657`
* `badasintended.megane.runtime.component.entity.PlayerHeadComponent`

#### `net.minecraft.class_1309`
* `badasintended.megane.runtime.component.entity.SpawnEggComponent`

#### `net.minecraft.class_1532`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1540`
* `mcp.mobius.waila.plugin.vanilla.FallingBlockComponent`

#### `net.minecraft.class_1533`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1688`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`


### Head Providers

#### `net.minecraft.class_1297`
* `mcp.mobius.waila.plugin.core.EntityComponent`

#### `net.minecraft.class_1309`
* `badasintended.megane.runtime.component.AlignResetComponent$Entity`
* `badasintended.megane.runtime.component.entity.PetOwnerComponent`

#### `net.minecraft.class_1540`
* `mcp.mobius.waila.plugin.vanilla.FallingBlockComponent`


### Body Providers

#### `net.minecraft.class_1309`
* `mcp.mobius.waila.plugin.core.EntityComponent`

#### `net.minecraft.class_1496`
* `net.pancham138.horseinfo.HorseInfo`


### Tail Providers

#### `net.minecraft.class_1297`
* `mcp.mobius.waila.plugin.core.EntityComponent`

#### `net.minecraft.class_1309`
* `badasintended.megane.runtime.component.entity.EntityInventoryComponent`
* `badasintended.megane.runtime.component.entity.StatusEffectComponent`


### Data Providers

#### `appeng.tile.AEBaseBlockEntity`
* `appeng.integration.modules.waila.PartWailaDataProvider`
* `appeng.integration.modules.waila.TileWailaDataProvider`

#### `net.minecraft.class_2609`
* `mcp.mobius.waila.plugin.vanilla.FurnaceComponent`

#### `net.minecraft.class_2248`
* `badasintended.megane.runtime.data.block.BlockInventoryData`
* `badasintended.megane.runtime.data.block.EnergyData`
* `badasintended.megane.runtime.data.block.FluidData`
* `badasintended.megane.runtime.data.block.ProgressData`

#### `aztech.modern_industrialization.pipes.impl.PipeBlockEntity`
* `aztech.modern_industrialization.compat.waila.PipeDataProvider`

#### `net.minecraft.class_2238`
* `badasintended.megane.runtime.data.block.BeaconData`

#### `net.minecraft.class_2619`
* `mcp.mobius.waila.plugin.vanilla.JukeboxComponent`

#### `net.minecraft.class_2586`
* `mcp.mobius.waila.plugin.core.BlockComponent`


## Entity
### Display Item Providers

#### `net.minecraft.class_1690`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1534`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1657`
* `badasintended.megane.runtime.component.entity.PlayerHeadComponent`

#### `net.minecraft.class_1309`
* `badasintended.megane.runtime.component.entity.SpawnEggComponent`

#### `net.minecraft.class_1532`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1540`
* `mcp.mobius.waila.plugin.vanilla.FallingBlockComponent`

#### `net.minecraft.class_1533`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1688`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`


### Head Providers

#### `net.minecraft.class_1297`
* `mcp.mobius.waila.plugin.core.EntityComponent`

#### `net.minecraft.class_1309`
* `badasintended.megane.runtime.component.AlignResetComponent$Entity`
* `badasintended.megane.runtime.component.entity.PetOwnerComponent`

#### `net.minecraft.class_1540`
* `mcp.mobius.waila.plugin.vanilla.FallingBlockComponent`


### Body Providers

#### `net.minecraft.class_1309`
* `mcp.mobius.waila.plugin.core.EntityComponent`

#### `net.minecraft.class_1496`
* `net.pancham138.horseinfo.HorseInfo`


### Tail Providers

#### `net.minecraft.class_1297`
* `mcp.mobius.waila.plugin.core.EntityComponent`

#### `net.minecraft.class_1309`
* `badasintended.megane.runtime.component.entity.EntityInventoryComponent`
* `badasintended.megane.runtime.component.entity.StatusEffectComponent`


### Data Providers

#### `net.minecraft.class_1309`
* `badasintended.megane.runtime.data.entity.EntityInventoryData`
* `badasintended.megane.runtime.data.entity.PetOwnerData`
* `badasintended.megane.runtime.data.entity.StatusEffectData`

</details>

if it shows one entry for every class then you still in wthit 2.7.0

**Comment by kabadesu** [comment]
I really have a feeling that this is being caused by something else, because a newer version of the whole pack isn't having this issue - but I'm not sure how to find the problem without adding and removing every mod.

<details>
<summary>Here's the kibe tank</summary>
![2021-05-02_08 30 38](https://user-images.githubusercontent.com/344908/116804952-310be400-ab23-11eb-8a28-890ef0c3b862.png)

</details>

<details>
<summary>Here's indrev mk4 cables</summary>
![2021-05-02_08 46 33](https://user-images.githubusercontent.com/344908/116804957-3701c500-ab23-11eb-8fea-6f0e8c0836fb.png)

</details>

<details>
<summary>Here's waila_handlers.md</summary>
# Waila Handler Dump
## Block
### Override Providers

#### `net.minecraft.class_2384`
* `mcp.mobius.waila.plugin.vanilla.InfestedBlockComponent`


### Display Item Providers

#### `net.minecraft.class_1690`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1688`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1540`
* `mcp.mobius.waila.plugin.vanilla.FallingBlockComponent`

#### `net.minecraft.class_1657`
* `badasintended.megane.runtime.component.entity.PlayerHeadComponent`

#### `net.minecraft.class_1532`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1534`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1533`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1309`
* `badasintended.megane.runtime.component.entity.SpawnEggComponent`


### Head Providers

#### `net.minecraft.class_1540`
* `mcp.mobius.waila.plugin.vanilla.FallingBlockComponent`

#### `net.minecraft.class_1297`
* `mcp.mobius.waila.plugin.core.EntityComponent`

#### `net.minecraft.class_1309`
* `badasintended.megane.runtime.component.AlignResetComponent$Entity`
* `badasintended.megane.runtime.component.entity.PetOwnerComponent`


### Body Providers

#### `net.minecraft.class_1496`
* `net.pancham138.horseinfo.HorseInfo`

#### `net.minecraft.class_1309`
* `mcp.mobius.waila.plugin.core.EntityComponent`


### Tail Providers

#### `net.minecraft.class_1297`
* `mcp.mobius.waila.plugin.core.EntityComponent`

#### `net.minecraft.class_1309`
* `badasintended.megane.runtime.component.entity.EntityInventoryComponent`
* `badasintended.megane.runtime.component.entity.StatusEffectComponent`


### Data Providers

#### `aztech.modern_industrialization.pipes.impl.PipeBlockEntity`
* `aztech.modern_industrialization.compat.waila.PipeDataProvider`

#### `net.minecraft.class_2609`
* `mcp.mobius.waila.plugin.vanilla.FurnaceComponent`

#### `appeng.tile.AEBaseBlockEntity`
* `appeng.integration.modules.waila.PartWailaDataProvider`
* `appeng.integration.modules.waila.TileWailaDataProvider`

#### `net.minecraft.class_2619`
* `mcp.mobius.waila.plugin.vanilla.JukeboxComponent`

#### `net.minecraft.class_2238`
* `badasintended.megane.runtime.data.block.BeaconData`

#### `net.minecraft.class_2248`
* `badasintended.megane.runtime.data.block.BlockInventoryData`
* `badasintended.megane.runtime.data.block.EnergyData`
* `badasintended.megane.runtime.data.block.FluidData`
* `badasintended.megane.runtime.data.block.ProgressData`

#### `net.minecraft.class_2586`
* `mcp.mobius.waila.plugin.core.BlockComponent`


## Entity
### Display Item Providers

#### `net.minecraft.class_1690`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1688`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1540`
* `mcp.mobius.waila.plugin.vanilla.FallingBlockComponent`

#### `net.minecraft.class_1657`
* `badasintended.megane.runtime.component.entity.PlayerHeadComponent`

#### `net.minecraft.class_1532`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1534`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1533`
* `mcp.mobius.waila.plugin.vanilla.EntityIconComponent`

#### `net.minecraft.class_1309`
* `badasintended.megane.runtime.component.entity.SpawnEggComponent`


### Head Providers

#### `net.minecraft.class_1540`
* `mcp.mobius.waila.plugin.vanilla.FallingBlockComponent`

#### `net.minecraft.class_1297`
* `mcp.mobius.waila.plugin.core.EntityComponent`

#### `net.minecraft.class_1309`
* `badasintended.megane.runtime.component.AlignResetComponent$Entity`
* `badasintended.megane.runtime.component.entity.PetOwnerComponent`


### Body Providers

#### `net.minecraft.class_1496`
* `net.pancham138.horseinfo.HorseInfo`

#### `net.minecraft.class_1309`
* `mcp.mobius.waila.plugin.core.EntityComponent`


### Tail Providers

#### `net.minecraft.class_1297`
* `mcp.mobius.waila.plugin.core.EntityComponent`

#### `net.minecraft.class_1309`
* `badasintended.megane.runtime.component.entity.EntityInventoryComponent`
* `badasintended.megane.runtime.component.entity.StatusEffectComponent`


### Data Providers

#### `net.minecraft.class_1309`
* `badasintended.megane.runtime.data.entity.EntityInventoryData`
* `badasintended.megane.runtime.data.entity.PetOwnerData`
* `badasintended.megane.runtime.data.entity.StatusEffectData`


</details>

**Comment by deirn** [comment]
do you update wthit on both the server and client?

**Comment by kabadesu** [comment]
Womp womp. I thought it might be like other mods where you can get away with only updating in the server. Sorry for wasting your time.
