### ISSUE TITLE
Indrev 1.9.14+ displays infinity energy.

### ISSUE THREAD

**Issue by Rover656** [badasintended/megane#24]
Indrev compatibility looks like it needs updating :)

![image](https://user-images.githubusercontent.com/20544390/119694809-7c28c680-be45-11eb-9ada-5f01cc7a59b9.png)

**Comment by deirn** [comment]
does it also shows 0/0 LF if you open the block and hover to the energy bar?

**Comment by Rover656** [comment]
Nope, the energy bar is rendering perfectly
![image](https://user-images.githubusercontent.com/20544390/119743455-d0ea3280-be81-11eb-9def-4525ffdedd5c.png)

**Comment by deirn** [comment]
do you have tech reborn or ae2 in your modlist?

**Comment by Rover656** [comment]
I do

**Comment by Rover656** [comment]
They both render perfectly

**Comment by deirn** [comment]
can you try [megane-team-reborn-energy-SNAPSHOT+0.1.0.jar.zip](https://github.com/badasintended/megane/files/6550186/megane-team-reborn-energy-SNAPSHOT%2B0.1.0.jar.zip)? put it alongside the current megane version

**Comment by Rover656** [comment]
I can indeed

**Comment by Rover656** [comment]
This has corrected the issue :)

**Comment by deirn** [comment]
nice
