### ISSUE TITLE
Crash with Tech Reborn looking at chest with lithium batteries or energy crystals

### ISSUE THREAD

**Issue by jangro** [badasintended/megane#35]
I'm on the latest version, 5.4.1 that came with the Valhelsia Fabric 1.0.8 update. It's on Tech Reborn 5.0.8-beta+build.111

I'm not sure this is megane or tech reborn, but I'll start here.  It got to the point where I couldn't get into the world, I assume because I was looking at something that triggered this. I removed Megane from the modpack and it's working again. 

I've narrowed it down... it happens when looking at a chest that has lithium batteries or energy crystals in it. I tested each item separately, both cause the crash. 

I tried going back to 5.3.1 and it still crashes. 

Here's the crash report
https://gist.github.com/jangro/d067625d3bffce0932fac0d39d3fff65

**Comment by jangro** [comment]
Posted over on tech reborn as well https://github.com/TechReborn/TechReborn/issues/2564

**Comment by jangro** [comment]
Final note: In my attempts to work around this, I tried various config file updates, including setting all of the modules (except vanilla) to false, and even blacklisting techreborn:lithium_ion_battery and techreborn:energy_crystal in the energy section. Still crashed.

only workaround is to not look at the chest. I tucked it away so I can still use megane.

**Comment by Technici4n** [comment]
Yup, megane's fix is probably better than what could have been done in TR. Thanks for the report anyway!
