### ISSUE TITLE
Game crash on latest release

### ISSUE THREAD

**Issue by xanthian** [badasintended/megane#36]
### Describe the issue

When looking at TechReborn machines game crashes immediately,
Likely a discrepancy between something in the new WTHIT and Megane
Rolling back to 3.10.1 works fine

### Log output

https://gist.github.com/xanthian/0dc989fdb21a15ab0440223cada9483f

**Comment by xanthian** [comment]
I don't think this is Megane issue, it only occurred since WTHIT was updated to 3.11.0.
Please move back :)

**Comment by deirn** [comment]
Megane uses to WTHIT internals, so it's megane issue. I can only blame myself on this though lol.

**Comment by xanthian** [comment]
Seems to be resolved with 3.11.1

**Comment by deirn** [comment]
It definetly still a problem on 3.11.1, though https://github.com/badasintended/megane/commit/947507b54605e782d8df3515d77541e12b2ba0aa fixes it.
