### ISSUE TITLE
Suggestion: Could you add Name of Items in Barrels in Modern Industrialization Please :)

### ISSUE THREAD

**Issue by KaneHart** [badasintended/megane#38]
Right now unless you know your icons well it can be hard for those of us especially those who might have vision issues and be a great accessibility upgrade if possible.

Thanks

![image](https://user-images.githubusercontent.com/425853/147027232-8f6ef7c9-c8d4-4a31-8392-82407095e823.png)

**Comment by deirn** [comment]
No, sorry. I don't put a special tooltip only for one mod. Megane is designed to be generic.

You can try asking the MI devs themselves, it already has a WTHIT integration for its pipe.
