### ISSUE TITLE
Flickering in chest contents overlay (probably a wthit issue)

### ISSUE THREAD

**Issue by Desempregago** [badasintended/megane#42]
### Describe the issue

https://user-images.githubusercontent.com/14002834/152647092-5bce01d7-3cdb-4cfd-93a4-486d88c6d294.mp4

### Log output

https://gist.github.com/Desempregago/b8ccd5ba896fe8cca2d6bda8ff332436

### Additional context

Some recent update made this happen (can't remember which one)

**Comment by Desempregago** [comment]
WTHIT 4.5.1
Megane 7.1.0

**Comment by MeeniMc** [comment]
It was not happening in 7.0.2/4.4.0

**Comment by ilkerbey-01** [comment]
still happening with latest updates, and I cant give any logs because theres no error
