### ISSUE TITLE
Error when looking at a chest from Tokenable Furnaces and Storage

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [badasintended/megane#43]
**MC** 1.18.2
**Fabric API** 0.51.1
**WTHIT** 4.9.0
**megane** 7.5.0
**[Tokenable Furnaces and Storage](https://www.curseforge.com/minecraft/mc-mods/tokenable-furnaces-and-storage/files/3765140)** 1.2.1

To reproduce simply go into creative, grab an iron chest from TFaS mod, place it down and look at it. Upgraded hoppers, furnaces and smokers don't produce the same issue.

Logs: https://gist.github.com/Footage2-Amply-Pounce/3c63960596b72e5f0cf65872875e3072

**Comment by deirn** [comment]
Fixed the error, but it will show the items from one side only.

Anyway, @Skylortrexler any reason why [`ExtraChestBlock`](https://github.com/Skylortrexler/SkyLib/blob/b72b57a7d60712bf07cb3154f6e78e73c820894b/src/main/java/website/skylorbeck/minecraft/skylorlib/storage/ExtraChestBlock.java) doesn't extend vanilla's `ChestBlock` and instead it extends `AbstractChestBlock`?  From a glance `ExtraChestBlock` looks like it just straight up a copy of `ChestBlock`.

**Comment by Skylortrexler** [comment]
Yeah past me is always less knowledgeable than current or even future me. 
https://github.com/Skylortrexler/SkyLib/commit/750080737e40571aa532aea833e9d6ee8d5c7445
https://github.com/Skylortrexler/tokenablefurnaces/commit/3fa3b69af78609d89634feacda3b7e1760617cf3

**Comment by deirn** [comment]
> Yeah past me is always less knowledgeable than current or even future me. Everything works after some retooling. [Skylortrexler/SkyLib@7500807](https://github.com/Skylortrexler/SkyLib/commit/750080737e40571aa532aea833e9d6ee8d5c7445) [Skylortrexler/tokenablefurnaces@3fa3b69](https://github.com/Skylortrexler/tokenablefurnaces/commit/3fa3b69af78609d89634feacda3b7e1760617cf3)

Cool, thank you for the changes!
