### ISSUE TITLE
Alloy Forgery Support

### ISSUE THREAD

**Issue by ardissaps** [badasintended/megane#47]
Would you please support Alloy Forgery? 

https://www.curseforge.com/minecraft/mc-mods/alloy-forgery

**Comment by deirn** [comment]
Versi minecraft berapa yang kau pake?

**Comment by ardissaps** [comment]
> Versi minecraft berapa yang kau pake?

1.18.2 :)

**Comment by ardissaps** [comment]
terimakasih! :)
