### ISSUE TITLE
[Mod Support] Chromatic Currents

### ISSUE THREAD

**Issue by ardissaps** [badasintended/megane#49]
Please support Chromatic Currents (multi-colored independent redstone dust) :
https://modrinth.com/mod/chromatic-currents

No hurry, Thank you very much.
1.18.2

**Comment by deirn** [comment]
Sorry, but I'm only adding compat for energy, item, fluid, and progress info.

**Comment by deirn** [comment]
It's included by WTHIT's built-in Minecraft plugin.

**Comment by ardissaps** [comment]
> It's included by WTHIT's built-in Minecraft plugin.

WTHIT also already works with :
https://modrinth.com/mod/wiredredstone
power on their redstone dust displayed on wthit

should I post on Chromatic Current side?

**Comment by deirn** [comment]
> WTHIT also already works with :
https://modrinth.com/mod/wiredredstone
power on their redstone dust displayed on wthit

Read its description, it has WTHIT integration built-in.

**Comment by ardissaps** [comment]
I see, so I should ask on their side, thanks for the response!
