### ISSUE TITLE
Not sure what this error means

### ISSUE THREAD

**Issue by NolanHewitt** [badasintended/megane#69]
<img width="425" alt="image" src="https://github.com/badasintended/megane/assets/52480898/dd63180a-e85e-4a8e-938f-df01e6056ca5">
Wanted to share this just incase.

**Comment by deirn** [comment]
Can you send your log?

**Comment by NolanHewitt** [comment]
[latest.log](https://github.com/badasintended/megane/files/14292874/latest.log)
I went into a world and looked at the machine which brings up this error, then exited to try and keep the log short and relevant to the issue.

The error in the log seems to be at 01:31:33

**Comment by deirn** [comment]
Try updating WTHIT to the latest version.

**Comment by deirn** [comment]
Oh, wait. I think there's some API classes missing on the WTHIT Quilt version.

**Comment by NolanHewitt** [comment]
I wasn't aware there was a newer version as my mod menu update checker hasn't been working for a bit. That's good to know. Since there's something missing with the WTHIT quilt version should I just keep an eye out on updates for that mod to resolve this then?

**Comment by deirn** [comment]
Should be released in a [few hours](https://github.com/badasintended/wthit/actions/runs/7912773376).

**Comment by NolanHewitt** [comment]
Thank you! I appreciate all the work you put into these mods!
