### ISSUE TITLE
ae2 Interface Fluids

### ISSUE THREAD

**Issue by xBolivar1** [badasintended/megane#70]
Hi! The ae2 Interface is trying to show me every fluid stored, which is kinda inconvinient I must say. See the picture below
![2024-02-29_18 28 26](https://github.com/badasintended/megane/assets/161753119/0bc430cd-617f-49d6-bc0c-85e393b5ae3d)

Details: 
Version: forge 20.1.0
Wthit Version: Forge 8.7.2

Tell me if you need anything else from me.

PS: I do not have any fluids stored

**Comment by deirn** [comment]
That doesn't look like the one Megane provides. Please check without Megane and see if the issue persists.

**Comment by xBolivar1** [comment]
I can confirm it is not Megane. It seems to come from WTHIT. I am emberased I didnt think to check that first. I have no other mod(s) who add such an identifyer.

**Comment by deirn** [comment]
It's not like the tooltip WTHIT adds by default either.

Try doing `/waila dump` command, it should spits out all the provider registered. Make a [gist](https://gist.github.com/) and send it here.

**Comment by xBolivar1** [comment]
That would be https://gist.github.com/xBolivar1/033b6a873cb9ffc132aa26c29b0d44ce

**Comment by deirn** [comment]
Try without Mekanism.

**Comment by xBolivar1** [comment]
It is indeed Mekanism. I'll file an appropiate bug report there. Is there anything you think I should mention besides what we learned here?

**Comment by deirn** [comment]
No, really. I do however plan on adding a more sophisticated compatibility module for Mekanism to Megane, but that's for another time. Anyway, I'm closing this issue.
