### ISSUE TITLE
Disconnect from the server when looking at Create trains (misunderstand)

### ISSUE THREAD

**Issue by HLHTHoldWind** [badasintended/megane#77]
Looking at copycat block will cause this issue

Internal Exception: java.lang.NullPointerException: Cannot invoke "mcp.mobius.waila.api.IData$Serializer.read(net.minecraft.class_2540)" because "serializer" is null

**Comment by deirn** [comment]
Does this happens especially with Megane installed, or just WTHIT?

**Comment by HLHTHoldWind** [comment]
> Does this happens especially with Megane installed, or just WTHIT?

with Megane, only install WTHIT will show copycat blocks correctly

**Comment by deirn** [comment]
Please send me the full log.

**Comment by HLHTHoldWind** [comment]
> Please send me the full log.

I have done some test with this problem. 

The error will not appear when using a pure environment (without other mods). 

Only the copycat blocks on the train will cause this issue. The copycat panel from original Create mod also has this problem.

I don't know which mod cause this issue when running with copycat blocks. But the fact is this issue will only appear when I'm looking at some copycat blocks on the train.

This is the client log: https://mclo.gs/TaiieSF

This is the server console output: https://mclo.gs/LwVuYOG

**Comment by HLHTHoldWind** [comment]
Sorry, not only the copycat blocks. 
But other blocks will not cause this issue immediately. After you look at other blocks on the train for a few seconds, you will also disconnect from the server with the same reason.

**Comment by HLHTHoldWind** [comment]
This problem will not happen under local singleplayer game.

**Comment by deirn** [comment]
Try without Replay Mod, I've seen some issue with Replay Mod and other custom packets.

**Comment by HLHTHoldWind** [comment]
> Try without Replay Mod, I've seen some issue with Replay Mod and other custom packets.

No effect, still having this problem after disabled Replay Mod. https://mclo.gs/11JDBSN

**Comment by deirn** [comment]
Oh, hmm... do you have Megane installed on the server? It needs to be installed there too.

**Comment by HLHTHoldWind** [comment]
> Oh, hmm... do you have Megane installed on the server? It needs to be installed there too.

Oh gosh, I didn't see that Megane is different with WTHIT, it's a serverside mod.
I will install it and have a try

**Comment by HLHTHoldWind** [comment]
Yes, it works well after install on the serverside.
Just a mistake

**Comment by deirn** [comment]
Maybe I'll create a handshake packet to make sure Megane is on the server
