### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Romz24** [badasintended/megane#8]
And so, I updated the mod to the latest version, but now the game crashes and it is impossible to enter it.

Minecraft version: **1.16.4**
Fabric loader: **0.10.7**
Fabric api: **0.25.7**
Mod version: **3.0.1 1.16.4**

[crash-2020-11-14_20.51.29-server.txt](https://github.com/badasintended/megane/files/5541248/crash-2020-11-14_20.51.29-server.txt)

**Comment by deirn** [comment]
oh oops got the mod name swapped out, ill fix it in the morning.

**Comment by deirn** [comment]
this is the problem btw https://github.com/badasintended/megane/blob/master/megane-impl/src/main/resources/fabric.mod.json#L31-L36 this

**Comment by deirn** [comment]
this is the problem
https://github.com/badasintended/megane/blob/master/megane-impl/src/main/resources/fabric.mod.json#L31-L36
